### PR TITLE
initial version of forthcoming change in UniParc API

### PR DESCRIPTION
**Pull request by ahmadshadab**
Hi @redaschi ,
Could you please take a look at the forthcoming changes notes for UniParc Light? I have kept it intentionally short and have mentioned only important APIs. Let me know if you have any comments. thanks

### CODE REVIEW

**Comment by redaschi** [comment]
Hi Shadab,

- I'm not familar with the github interface - can you please merge/add this into the 2024_05 branch and then I can edit it locally?
- Regarding "UniProt API", you are talking about the "Proteins API" at https://www.ebi.ac.uk/proteins/api/doc/#uniparcApi, right? 
- There are sections that seem redundant (or I misunderstand them):
Bulk APIs (/uniparc/search or /uniparc/stream) responses will no longer include cross-references.
...
Search API Adjustments:
    The /uniparc/search endpoint will return only light UniParc objects without cross-references.
 _= redundant with first sentence?_ 
Streaming and Bulk Endpoints:
    Endpoints like /uniparc/stream and /uniparc/upis will only return light entries, excluding cross-references.
 _= partially redundant with first sentence? I don't understand the difference between "Streaming" and "Bulk". I find help page that talk about stream https://www.uniprot.org/help?query=streaming, but none mentions "Bulk"_ 
- I know this comes a bit late: could we still rename "light" to "core" (core data = sequence and interpro matches)?

Cheers, Nicole

**Comment by ahmadshadab** [comment]
Hi @redaschi ,
When i say UniProt API, I don't refere Proteins API but the new APIs which we have developed as a part of new website.
I have left light in the endpoint because we are using light in uniref as well.
Please let me know if you have any other question.

**Comment by redaschi** [comment]
I've revised/shortened it. I moved the "all current search fields ..." to /uniparc/search, as I assumed this applies only to that endpoint? If not, pls move it back into a separate bullet point.
I hope I did not mess-up something else, pls check and correct if necessary.

**Comment by redaschi** [comment]
I've revised/shortened it. I moved the "all current search fields ..." to /uniparc/search, as I assumed this applies only to that endpoint? If not, pls move it back into a separate bullet point.
I hope I did not mess-up something else, pls check and correct if necessary.

**Comment by redaschi** [comment]
Just added a sentence on uniparc.xsd

**Comment by ahmadshadab** [comment]
Thanks @redaschi I have moved the comment about search field to main list. It is applicable to all APIs.

**Comment by redaschi** [comment]
OK, I moved it out of the bullet list since you say it applies to all APIs (I thought it was only for the changed ones). I think/hope it is now OK :-)

**Pull request merged**
